#ifndef CONFIG_H
#define CONFIG_H

#define CONFIG_DEFAULT_KEYBOARD_INPUT_EVENT "/dev/input/event0"
#define CONFIG_DEFAULT_MOUSE_INPUT_EVENT "/dev/input/mouse0"
#define CONFIG_DEFAULT_TIMEOUT_MS (2 * 1000)
#define CONFIG_DEFAULT_SCHEDULE_ON_HOUR 20
#define CONFIG_DEFAULT_SCHEDULE_ON_MINUTE 00
#define CONFIG_DEFAULT_SCHEDULE_OFF_HOUR 7
#define CONFIG_DEFAULT_SCHEDULE_OFF_MINUTE 00

#define CONFIG_ENABLE_MOUSE_EVENT
#define CONFIG_ENABLE_KEYBOARD_EVENT
#define CONFIG_ENABLE_MOUSE_LOWER_BRIGHTNESS
#define CONFIG_ENABLE_SCHEDULE
// #define CONFIG_DISABLE_VERBOSE

#endif