name: C CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make clang-tidy
      run: make clang-tidy
