name: C CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
<<<<<<< HEAD
    - uses: actions/checkout@v3
=======
>>>>>>> f9f49b2 (Chane checkout to v3)
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make clang-tidy
      run: make clang-tidy
