name: C CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
<<<<<<< HEAD
    - uses: actions/checkout@v4
=======
    - uses: actions/checkout@v3
>>>>>>> 472fdb4 (Change gh actions)
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make clang-tidy
      run: make clang-tidy
